from .prompts import (
    SYSTEM_PROMPT_MULTI_FACT_BRIEF,
    SYSTEM_PROMPT_MEDIA_ANALYSIS,
    SYSTEM_PROMPT_CONTENT_RELEVANCE,
    SYSTEM_PROMPT_METADATA_RELEVANCE,
    SYSTEM_PROMPT_QUERY_PLAN,
    SYSTEM_PROMPT_TAVILY_QUERY_EXPANSION,
    SYSTEM_PROMPT_WEIBO_QUERY_EXPANSION,
    SYSTEM_PROMPT_FACT_EXTRACTION,
    SYSTEM_PROMPT_FIRST_SEARCH,
    SYSTEM_PROMPT_FIRST_SUMMARY,
    SYSTEM_PROMPT_REFLECTION,
    SYSTEM_PROMPT_REFLECTION_SUMMARY,
    SYSTEM_PROMPT_REPORT_FORMATTING,
    SYSTEM_PROMPT_REPORT_STRUCTURE,
)

__all__ = [name for name in globals() if name.startswith("SYSTEM_PROMPT_")]
